apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-staging
namePrefix: staging-

resources:
  - ../../base/guestbook

replicas:
  - name: guestbook-ui
    count: 2

patchesStrategicMerge:
  - deployment-patch.yaml
