apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-production
namePrefix: prod-

resources:
  - ../../base/guestbook

replicas:
  - name: guestbook-ui
    count: 3

patchesStrategicMerge:
  - deployment-patch.yaml