apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-dev
namePrefix: dev-

resources:
  - ../../base/guestbook

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - environment=development
      - log_level=debug